//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vettel.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vettel.View.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vettel is UDP protocol client and server application. Client allows to listen messages from Server..
        /// </summary>
        internal static string ApplicationInfo {
            get {
                return ResourceManager.GetString("ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application running mode:.
        /// </summary>
        internal static string ChooseMode {
            get {
                return ResourceManager.GetString("ChooseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application starts work in Client mode..
        /// </summary>
        internal static string ClientMode {
            get {
                return ResourceManager.GetString("ClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type IP address to send:.
        /// </summary>
        internal static string InputIpAddress {
            get {
                return ResourceManager.GetString("InputIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type port to listen:.
        /// </summary>
        internal static string InputPort {
            get {
                return ResourceManager.GetString("InputPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevied message: .
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message to send:.
        /// </summary>
        internal static string MessageToSend {
            get {
                return ResourceManager.GetString("MessageToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application starts work in Server mode..
        /// </summary>
        internal static string ServerMode {
            get {
                return ResourceManager.GetString("ServerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vettel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is going to work on IP address: .
        /// </summary>
        internal static string WorkingIp {
            get {
                return ResourceManager.GetString("WorkingIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is going to work on port: .
        /// </summary>
        internal static string WorkingPort {
            get {
                return ResourceManager.GetString("WorkingPort", resourceCulture);
            }
        }
    }
}
